// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cDOnc6xaYHcDPxdjN2gvl2duN96bvRA',
    appId: '1:1004125384470:android:01bf939facbf31e1016a37',
    messagingSenderId: '1004125384470',
    projectId: 'moncvapp',
    databaseURL: 'https://moncvapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moncvapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgE0qS4sRpI4Lu7N0E3g_msEOv1qFUc4s',
    appId: '1:1004125384470:ios:447d2f354324da35016a37',
    messagingSenderId: '1004125384470',
    projectId: 'moncvapp',
    databaseURL: 'https://moncvapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moncvapp.firebasestorage.app',
    iosBundleId: 'com.example.cvApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1d6_tEO2HjDMLP4RKgdCQW0VcDbW2gUU',
    appId: '1:1004125384470:web:d238ac9ff1f07eeb016a37',
    messagingSenderId: '1004125384470',
    projectId: 'moncvapp',
    authDomain: 'moncvapp.firebaseapp.com',
    databaseURL: 'https://moncvapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moncvapp.firebasestorage.app',
    measurementId: 'G-WTH3L318B8',
  );

}